### ISSUE TITLE
Add lang of html

### ISSUE THREAD

**Issue by iampaul83** [Yu-Jack/yu-jack.github.io#3]
每次打開都問要不要翻譯～

![screen shot 2017-10-18 at 1 15 00 am](https://user-images.githubusercontent.com/4386549/31678795-dfda353a-b334-11e7-9378-e41e8977cbd3.png)

1. 在 _config.yml 裡面設定 language 為 zh-TW
2. 在 themes/landscape/layout/_partial/head.ejs 設定 `<html lang=<%= config.language %>>`

我上次改的 commit: https://github.com/iampaul83/react_923/commit/817e233a2f1c9ed01c7096e367e38a256e7afe6d#diff-8576d4d7f2fd44e7f08206c4af593605

**Comment by Yu-Jack** [comment]
Ok, let me try this
